### PR TITLE
Fix #25 - Updates for news 9

### LINKED ISSUE #25: Support for news 9 (WIP list ...)
See news changelog: https://github.com/georgringer/news/blob/master/Documentation/Misc/Changelog/9-0-0.rst

Using:

* calendarize_news: current master
* calendarize: 11.0.2
* news: 9.0.0
* TYPO3 10.4 latest

-----

Some changes necessary (WIP):

* news: [LinkViewHelper](https://github.com/georgringer/news/blob/master/Classes/ViewHelpers/LinkViewHelper.php) now contains typehint must be changed in XCLASS'd VH in calendarize_news

`Fatal error: Declaration of HDNET\CalendarizeNews\Xclass\NewsLinkViewHelper::render() must be compatible with GeorgRinger\News\ViewHelpers\LinkViewHelper::render(): ?string in /var/www/t3coredev10x/typo3conf/ext/calendarize_news/Classes/Xclass/NewsLinkViewHelper.php on line 32`

### PR DESCRIPTION
**Pull request by sypets**

### CODE REVIEW

**Comment by sypets** [comment]
I added a [return to detailAction](https://github.com/lochmueller/calendarize_news/pull/26/commits/58a683a9435e43ad09f0836a0fdfa7df96482932). It is not a fix but avoids phpstan warning.

What is good, phpstan detected the problem fixed in https://github.com/lochmueller/calendarize_news/pull/26/commits/aa030d46b7ae083c6bc242d9405c81bb4c23a9b3 when switching to news v9 without applying the patch, so looks like adding phpstan was worth the trouble.

I'll give it another go next week on our site ...

**Comment by lochmueller** [comment]
Great. Merge this one. If I should also release a new version, send me a short note

**Comment by sypets** [comment]
We have been using this now in production for a while without problems:

```
andreaskastl/calendarize-address,dev-update-requirement-calendarize-115c642ac..
georgringer/news,9.1.0
lochmueller/calendarize,11.0.2
lochmueller/calendarize-news,dev-masterff81c0a
lochmueller/calendarize-pages,3.2.0

```

In case you might want to create a release for new dependency ...

**Comment by lochmueller** [comment]
Hey @sypets 
pushed version 6.2.0 to Packagist&TER.
Regards,
Tim

**Pull request merged**
